LOAD DATA INFILE "C:/Users/Desenvolvimento.DESKTOP-CJ165MI/Desktop/SENAI/3DES/PROJETOS/AULA15(OSs)/docs/colaboradores.csv"
INTO TABLE colaborador
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/Desenvolvimento.DESKTOP-CJ165MI/Desktop/SENAI/3DES/PROJETOS/AULA15(OSs)/docs/oss.csv"
INTO TABLE os
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/Desenvolvimento.DESKTOP-CJ165MI/Desktop/SENAI/3DES/PROJETOS/AULA15(OSs)/docs/comentarios.csv"
INTO TABLE comentario
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

